name: Release Pre-release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Pre-release
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Version From Package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

      - name: Create release zip
        run: zip -r "release-${{ steps.get-version.outputs.version }}.zip" .

      - name: Set Artifact Path
        run: echo "ARTIFACT_PATH=release-${{ steps.get-version.outputs.version }}.zip" >> $GITHUB_ENV
      
      - name: Check if tag exists
        id: check_tag
        run: |
          set -e
          if git rev-parse "v${{ steps.get-version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.get-version.outputs.version }}" exists.
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag v${{ steps.get-version.outputs.version }}" does not exist.
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Create GitHub Release
        if: env.TAG_EXISTS != 'true'
        id: create_github_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ steps.get-version.outputs.version }}"
          release_name: "Pre-release ${{ steps.get-version.outputs.version }}"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: "release"
          path: "${{ env.ARTIFACT_PATH }}"
