name: Release Pre-release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Pre-release
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest version from package.json
        id: get_version
        run: echo "VERSION=$(node -p \"require('./package.json').version\" | tr -d \"[:punct:]\")" >> $GITHUB_ENV

      - name: Create release zip
        run: zip -r "release-$VERSION.zip" .

      - name: Create GitHub Release
        id: create_github_release
        uses: actions/create-release@v1
        with:
          tag_name: "v$VERSION"
          release_name: "Pre-release $VERSION"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: "release"
          path: "release-$VERSION.zip"
