name: Release Pre-release

on:
  push:
    branches:
      - main # Replace with your default branch if different

jobs:
  release:
    name: Release Pre-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create release zip
        id: create_release
        run: |
          mkdir -p release
          zip -r release/release-${{ steps.get_version.outputs.version }}.zip .

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: pre-release-${{ steps.get_version.outputs.version }}
          release_name: Pre-release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ steps.get_version.outputs.version }}
          path: release/release-${{ steps.get_version.outputs.version }}.zip
