name: 'Build for Windows'
inputs:
  name: # vlc-rpc-v${{steps.get-version.outputs.version}}-nightly${{env.NOW}}-bundled-win-x64
    required: true
runs:
  using: "composite"
  steps:
    - name: Package for Windows
      run: |
        mkdir -p .dist/zipped/
        mkdir -p .dist/win-x64/
        cp -rv * .dist/win-x64/
        wget -P .dist/win-x64 https://nodejs.org/download/release/latest/win-x64/node.exe
        zip -r ".dist/zipped/${{inputs.name}}.zip" .dist/win-x64
      shell: bash
    - name: Archive Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.name}}
        path: |
          .dist/win-x64
